version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
